// =====================================================================  AKTE (Modul „akte“): Die Akte Abgrund – die Durchschläge der Whistleblowerin
// Dr. Edda Brand, 1994–2012 Ärztin der Außenstelle Lost Eyengless der Bundesstelle für Rückführung (BfR, im Ort „das Amt“), hat vor der Auflösung
// zehn Durchschläge versteckt – dort, wo Kinder spielen und Erwachsene nicht hinsehen. Sie erzählen, was die Regierung geheim hält:
// den Vertrag von 1958, die gefälschte UFO-Schlagzeile, die Bergungen nicht menschlicher Wesen in den Zyklusnächten, die Rückläufer (Kopien),
// Peter Kranz und die Versuchsreihe K (der Zahn-Mann aus Kapitel 2), die Sperre von 2009, Akte 08 – und das Ende 2012.
// Nebenstory zum Erkunden (Nebenaufgabe „Die Akte Abgrund“); jeder Durchschlag ist ein Fund, alle zehn geben die ganze Geschichte und eine Belohnung.
const AKTE_S = { ready: false, docs: [], placed: false };
const AKTE = [ // [Nr, Titel, Ort (Anker: x, yProbe, z | Funktion), Text] – Fassung 3: Texte wortgleich aus dem LWO-Dossier 5.1 (7 = Akte 08 im Amt, 9 = Versuchsreihe K auf dem Hochsitz; Orte unverändert)
  [1, 'Wer das findet', () => [22.6, 1.2, 69.2], 'Wenn du das liest, hat keiner aufgeräumt. Gut.\nIch heiße Edda Brand. Ich war achtzehn Jahre lang Ärztin in einer Behörde, die es nie gegeben hat. Ich habe Kinder gewogen, die aus einem Licht kamen, und aufgeschrieben, ob sie noch Kinder waren.\nIch lege zehn Durchschläge aus. Dort, wo Kinder spielen und Erwachsene nicht hinsehen. Lies sie alle. Dann entscheide selbst, ob du Angst haben willst.'],
  [2, 'Verwalten, nicht beseitigen', () => [-45.8, 1.2, 90.4], 'Abschrift eines Vermerks aus Bonn, 1958: „Das Phänomen Abgrund ist nicht zu beseitigen, sondern zu verwalten.“ Gegengezeichnet: Dr. Theodor Seiler. Der Absender ist geschwärzt. Ich habe unter der Schwärzung gefühlt: ein Kreis, ein Auge, eine Flamme.\nDie Bundesstelle gehört nicht dem Bund. Sie gehört Leuten, die sich 1947 geschworen haben, dass die Welt nie erfährt, was sie in den Trümmern gefunden haben. Sie nennen sich hellwach. Ich habe sie nie schlafen sehen.\nRückführung heißt nicht Rettung. Rückführung heißt: Wir holen ab, was zurückkommt, und wir schreiben auf, ob es ein Mensch ist.'],
  [3, 'Die Schlagzeile', () => [112.2, 1.2, 23.4], '„UFO über dem Abgrund“ stammt von uns. Seiler hat sie dem Laternenboten 1975 diktiert, und Wolter hat den Artikel geschrieben, der sie eine Woche später zu Sumpfgas erklärt. Beides. Damit man erst lacht und dann gähnt.\nWer von Ufos redet, wird ausgelacht. Wer ausgelacht wird, fragt nicht nach sieben Kindern.\nPeter Kranz kam damals drei Tage später zurück. Mit braunen Augen statt blauen. Seine Mutter hat es bemerkt. Wir haben ihr gesagt, das komme vom Schock. Sie hat ihn trotzdem behalten. Sie hat ihn trotzdem geliebt. Das haben wir auch aufgeschrieben.'],
  [4, 'Die Bergungen', () => [-129.2, 1.2, -23.6], 'In jeder offenen Nacht steht ein Trupp mit Ketten am Rand. Sie tragen Eisen über dem Kopf, weil ein Ritter das auch tut, und sie glauben, es sei dasselbe. Nicht alles, was an der Kette hängt, ist ein Kind.\n1975: vier Kühe ohne Augen, glatte Ränder, in die Flanke gebrannt sieben Kreise und ein halber. Eine Glocke, die zwei Tage nicht aufhört zu schwingen. 1992: ein Hund, der nur rückwärts läuft. Etwas Formloses, das sich hinstellt wie ein Hirsch und mit Seilers Stimme redet. Und Gefreiter Hofer, der mit einem Gesicht zurückkam, das seine Frau nicht kannte.\nIm Protokoll steht „auf eigenen Wunsch versetzt“. Ich habe seine Akte gesehen. Da ist kein Wunsch drin. Nur Maße.'],
  [5, 'Die Rückläufer', () => [-110.4, 1.2, 27.8], 'Intern heißen sie R-Fälle. Rückläufer. Das Dorf sagt Wechselbalg, und das Dorf hat das bessere Wort.\nSie essen, schlafen, lieben ihre Eltern. Sie bluten. Sie werden nie krank. Wenn im Radio 31,10 rauscht, zählen sie im Schlaf leise mit, bis siebzehn, und fangen von vorn an.\nDienstanweisung 4: beobachten, nicht aufklären. Denn wer weiß, was er ist, durch den sieht es. Das hat uns 1992 ein Mann beigebracht, der seine eigene Akte gelesen hat.'],
  [6, 'Peter Kranz', () => [127.6, 1.2, -27.2], 'Peter Kranz hat 1992 seine eigene Akte gelesen. Jemand hat sie ihm gegeben. Ich weiß bis heute nicht, wer. Ich habe zwei Vermutungen und schreibe keine auf: Die eine Frau hat zwei Söhne, und der andere ist im selben Sommer in den Nebel gegangen.\nIn derselben Nacht hat das Licht durch ihn hindurchgesehen wie durch ein Fenster. Seiler hat ihn unter die Erde gebracht, weil es dort nicht hinsieht. Das Amt hat ihn nicht getötet. Man tötet keine Beweise. Man macht Versuche mit ihnen.\nWas danach aus ihm wurde, steht unter „K“.'],
  [7, 'Akte 08', () => (typeof C2 !== 'undefined' ? [C2.x + 86.1, 1.2, C2.z - 1.1] : null), 'Am fünften August 2009, drei Uhr dreizehn, brachte der Ritter den letzten Jungen heraus. Er war nicht der, der gegangen war.\nDer Ritter hat es nicht gemerkt. Wir schon: andere Blutgruppe als vorher, in der linken Handfläche eine halbrunde Narbe, die der Junge vorher nicht hatte, und die der Ritter an derselben Stelle hat. Der Junge, der gegangen war, hatte blaue Augen.\nWir haben ihm eine Nummer gegeben, 08, und seiner Mutter nichts gesagt. Sie hat es am ersten Morgen gewusst. Sie hat ihn behalten, wie ihre Mutter ihren Bruder behalten hat. Den Rest findest du unten, im Messraum.'],
  [8, 'Die Sperre', () => [144.2, 1.2, 4.1], 'Wir kannten das Jahr. Den Tag hat uns die Liste verraten, denn die Liste haben wir selbst gemacht: sieben Kugeln, sieben Lampions, sieben Unterschriften. Frau Wendt hat gezogen. Sie hat die Kugel ihres Jungen gezogen und nicht neu gezogen. Ich war dabei.\nAm siebenundzwanzigsten Juli wollten Familien wegfahren. Die Sperre stand da schon: „Unwetterwarnung“. Wer durchbrechen wollte, blieb stehen. Die weißen Autos da draußen sind keine Unfälle.\nAnweisung: Beobachtung statt Evakuierung. Ich habe sie abgezeichnet. Ich schreibe es auf, weil ich es nicht ungeschrieben machen kann.'],
  [9, 'Versuchsreihe K', () => (typeof TIEF !== 'undefined' ? [TIEF.stand.x - .5, 3.9, TIEF.stand.z + .4] : null), 'K wie Kopie. Ziel: aus dem Wechselbalg das verlorene Kind zurückholen. Mittel: Sternfleisch aus zwei Gläsern, Kälte, Licht in Stößen, Tonbänder mit der Stimme seiner Schwester Marion.\nK-1, Peter Kranz. Das Fleisch hat ihn umgebaut, aber nicht nach dem, der er war. Nach dem, was ein kleines Kind von ihm im Kopf hatte: der Onkel, der immer lacht. Zähne, wo keine hingehören. Er fühlt alles. Ergebnis 41: Er hat meine Hand gehalten und „Bruder“ gesagt. Am dritten März 2011 hat er das Gitter aus der Wand gerissen. Zwei Pfleger. Offiziell ein Gasleck.\nK-2 war ein Junge ohne Namen, 1958. Er ist gestorben. K-3 steht schon auf dem Deckel einer leeren Akte: Brandt, L. Wolter sagt, mit ihm holen wir seine Schwester zurück. Wolter sagt das, seit es diese Außenstelle gibt.'],
  [10, 'Die Auflösung', () => (typeof ANW_HALL !== 'undefined' ? [ANW_HALL.x + 5.6, 1.2, ANW_HALL.z - 3.4] : null), 'Heute wird die Außenstelle aufgelöst. Die Akten gehen nach unten, zu den Wassern, dorthin, wo nichts gefunden wird. Die echten hat Seiler in seine Villa geschafft. Er hat acht Schlösser angebracht und sagt, 2026 komme jemand, der hinsehen will.\nIch fahre heute Nacht nach Hamburg, zu einer Zeitung. Ich gebe den Brief dem Postboten mit, weil ich meinem eigenen Auto nicht traue. Wenn du nie etwas davon gehört hast, ist einer von uns beiden nicht angekommen.\n— E. B., 19. November 2012'],
];
const akte_has = n => story.lore.some(l => l.key === 'akte_' + n);
// Kapitel-Sperren (PK-A A14–A20): ab welchem Kapitel ein Durchschlag ausliegt (fehlt = ab Kapitel 1)
const AKTE_AB = { 5: 3, 6: 3, 7: 2, 8: 3, 9: 6, 10: 4 };
// Durchschlag 7 liegt NICHT mehr offen im langen Gang (Kap. 2 hätte die Wendung vor Akte 08 verraten): er kommt erst als Umschlag aus dem Amt (amt_akte08 → umschlag7 → akte_umschlag7) – 10/10 zählt unverändert über story.lore
const akte_offen = n => n === 7 ? false : kapAb(AKTE_AB[n] || 1);
function akte_sperre() { for (const d of AKTE_S.docs) { const on = akte_offen(d.n), i = interactables.indexOf(d.hit); d.m.visible = on && !akte_has(d.n) && !d.weg; if (on && i < 0) interactables.push(d.hit); else if (!on && i >= 0) interactables.splice(i, 1); } }
const akte_n = () => AKTE.filter(a => akte_has(a[0])).length;
function akte_tex() { return tex(cnv(256, (c, w) => { c.fillStyle = '#b89a6a'; c.fillRect(0, 0, w, w); for (let i = 0; i < 60; i++) { c.fillStyle = `rgba(60,40,20,${rand(.03, .12)})`; c.fillRect(rand(0, w), rand(0, w), rand(4, 40), rand(2, 10)); }
  c.fillStyle = '#efe8d8'; c.fillRect(30, 18, 196, 60); c.fillStyle = '#2a2a2a'; c.font = 'bold 22px Courier New'; c.textAlign = 'center'; c.fillText('BfR · AST LE', w / 2, 44); c.font = '16px Courier New'; c.fillText('DURCHSCHLAG', w / 2, 66);
  c.save(); c.translate(w / 2, 160); c.rotate(-.18); c.strokeStyle = 'rgba(170,30,25,.85)'; c.lineWidth = 5; c.strokeRect(-92, -26, 184, 52); c.fillStyle = 'rgba(170,30,25,.85)'; c.font = 'bold 28px Courier New'; c.fillText('VERTRAULICH', 0, 10); c.restore();
  akte_auge(c, w / 2, 220, 22, 'rgba(30,30,30,.75)'); }), true); } // Fassung 3 (AP-11): das Auge unter dem Kopf
function akte_auge(c, x, y, r, col) { c.save(); c.strokeStyle = col; c.fillStyle = col; c.lineWidth = Math.max(1.5, r * .12); c.beginPath(); c.arc(x, y, r * 1.35, 0, 7); c.stroke(); // Kreis, Auge, Flamme (LWO-Zeichen)
  c.beginPath(); c.moveTo(x - r, y); c.quadraticCurveTo(x, y - r * .8, x + r, y); c.quadraticCurveTo(x, y + r * .8, x - r, y); c.stroke(); c.beginPath(); c.arc(x, y, r * .3, 0, 7); c.fill();
  c.beginPath(); c.moveTo(x, y - r * 1.05); c.quadraticCurveTo(x + r * .22, y - r * .7, x, y - r * .5); c.quadraticCurveTo(x - r * .22, y - r * .7, x, y - r * 1.05); c.fill(); c.restore(); }
const AKTE_KOPF = (() => { try { return cnv(64, (c, w) => { c.clearRect(0, 0, w, w); akte_auge(c, 32, 34, 17, 'rgba(25,25,25,.85)'); }).toDataURL(); } catch (e) { return ''; } })();
WORLD_MODS.push(['Die Akte Abgrund', async () => {
  const S = AKTE_S, mat = new THREE.MeshStandardMaterial({ map: akte_tex(), roughness: .85 });
  for (const [n, title, at] of AKTE) { const p = at(); if (!p) continue; const m = new THREE.Mesh(new THREE.BoxGeometry(.24, .012, .32), mat); m.position.set(p[0], .02, p[2]); m.rotation.y = rand(-.6, .6); m.castShadow = true; m.receiveShadow = true; m.userData.noCol = true; scene.add(m);
    const hit = box(.45, .3, .5, p[0], .15, p[2], hidden, { cast: false }); interact(hit, () => akte_has(n) ? `Durchschlag ${n} / 10` : 'Ein Umschlag, gestempelt VERTRAULICH', () => akte_lesen(n));
    S.docs.push({ n, m, hit, x: p[0], yP: p[1], z: p[2] }); if (typeof hintAdd === 'function') hintAdd({ id: 'akte_' + n, x: p[0], y: 0, z: p[2], kind: 'geheim', near: 24, open: () => !akte_has(n) && akte_offen(n) }); }
  story.side.akte = { title: 'Wo Erwachsene nicht hinsehen', desc: 'Jemand aus dem Amt hat Durchschläge versteckt. Es muss noch mehr davon geben.', state: 'hidden' };
  akte_sperre(); S.ready = true;
}]);
function akte_lesen(n) {
  const [, title, , txt] = AKTE.find(a => a[0] === n), html = '<span style="display:block;text-align:center;font:700 .82em \'Courier New\',monospace;letter-spacing:.14em;border-bottom:1px solid rgba(40,30,20,.45);padding-bottom:4px;margin-bottom:10px">BfR · AST LE · DURCHSCHLAG · VERTRAULICH' +
    (AKTE_KOPF ? `<img src="${AKTE_KOPF}" alt="" style="display:block;width:30px;height:30px;margin:4px auto 0;padding:0;background:none;box-shadow:none!important;transform:none;opacity:.8">` : '') + '</span>' + // Fassung 3 (AP-11): Kopf jedes Blatts, klein das Auge
    '<span style="font-family:\'Courier New\',monospace;font-size:.93em;line-height:1.55">' + txt.replace(/\n/g, '<br>') + '</span>';
  if (!akte_has(n)) { story.lore.push({ key: 'akte_' + n, title: `Akte Abgrund ${n} / 10 · ${title}`, html }); Audio.paper(); sideStart('akte'); const c = akte_n();
    if (n !== 7 && typeof lwo_trust === 'function') lwo_trust(-2, 'akte_' + n); // 5.1: Durchschlag aufheben (außer 7) −2, je einmal
    story.side.akte.desc = `Die Durchschläge der Ärztin Edda Brand: was das Amt vertuscht hat. Gefunden: ${c} / 10.` + (c < 10 ? ' Sie liegen dort, wo Kinder spielen und Erwachsene nicht hinsehen.' : '');
    questPop(`AKTE ABGRUND ${c} / 10`, title); const d = AKTE_S.docs.find(x => x.n === n); if (d) d.m.visible = false;
    const G = { 1: 'Eine Ärztin vom Amt. Sie wollte, dass das jemand findet. Sie hat nicht mit mir gerechnet, aber gut.', 2: 'Verwalten. Wie Parkplätze.', 3: 'Die UFO-Schlagzeile. Die haben sie selbst geschrieben. Vegas hat recht. Vegas hat immer recht, das ist das Schlimme.', 4: 'Nicht alles, was zurückkommt, ist ein Kind. … Die Kuh. Sie haben die Kuh vermessen.', 5: 'Bis siebzehn. Ich zähle im Schlaf. Lucy hat mich damit aufgezogen, jahrelang.', 6: 'Onkel Peter. Sie haben ihn eingesperrt, weil er es wusste. Unter die Erde. Wo sie nicht hinsieht.', 7: '08. Eine halbrunde Narbe in der linken Hand. … Ich hab auch eine. ‚Fahrradunfall‘, hat Mama gesagt.', 8: 'Sie wussten es. Sie haben die Straße zugemacht und zugesehen. Und Hilde hat ihren eigenen Sohn gezogen.', 9: 'K-3. Brandt, L. Das bin ich. Sie wollten mich umbauen wie Onkel Peter. Nach dem Bild, das … wer hat ein Bild von mir im Kopf?', 10: 'Dem Postboten. Sie hat den Brief Günther Maas gegeben.' }[n]; // Gedanken: LWO-Dossier 5.1
    if (G && typeof gedanke === 'function') gedanke('akte_' + n, G, 1500, 3);
    if (c === 10) setTimeout(() => akte_fertig(), 1400); if (typeof saveGame === 'function' && state.started) saveGame(curChapter()); }
  const sieben = n !== 7 && kapAb(3) && story.items.includes('umschlag7') && !akte_has(7); // AP-25: der Umschlag aus dem Amt (Kap. 2 ungeöffnet eingesteckt) – beim nächsten Durchschlag aufmachen
  openNote(`Durchschlag ${n} / 10 · ${title}`, html, null, sieben ? () => setTimeout(akte_umschlag7, 500) : undefined);
}
function akte_umschlag7() { if (akte_has(7) || !story.items.includes('umschlag7')) return; story.items = story.items.filter(k => k !== 'umschlag7');
  if (typeof gedanke === 'function') gedanke('akte_umschlag7', 'Derselbe Kopf wie auf dem Umschlag aus dem Amt. Den hab ich nie aufgemacht.', 0, 3); setTimeout(() => akte_lesen(7), 1800); }
function akte_fertig() {
  if (story.lore.some(l => l.key === 'akte_ganz')) return;
  const html = 'Zehn Durchschläge. Zusammen ergeben sie eine Akte, die es offiziell nie gab. Edda Brand ist nie in Hamburg angekommen. Ihr Brief auch nicht.\n\nIm letzten Umschlag, ganz unten, drei Batterien und ein Zettel in ihrer Handschrift: <span class="hand">„Für den Weg nach unten. Nimm Licht mit.“</span>';
  story.lore.push({ key: 'akte_ganz', title: 'Wo Erwachsene nicht hinsehen (vollständig)', html }); addBattery(3); sideDone('akte', 'Alle zehn Durchschläge. Edda Brand ist nie in Hamburg angekommen.'); openNote('Die Akte Abgrund', html);
  if (typeof gedanke === 'function') gedanke('akte_ganz', 'Sie ist nie angekommen. Dann muss ich es sein.', 3000, 3);
}
WORLD_TICK.push(() => { // Umschläge auf die echte Oberfläche legen (Tisch, Plattform, Boden), sobald die Kollision steht
  const S = AKTE_S; if (!S.ready) return; const k = kap(); if (k !== S.k) { S.k = k; akte_sperre(); } // Kapitelwechsel (auch Laden/Kapitelwahl): Sperren nachziehen
  if (S.placed || typeof SOL === 'undefined' || !SOL.items.length) return; S.placed = true;
  for (const d of S.docs) { const g = solidGround(d.x, d.yP, d.z), y = g > -1 ? g + .012 : .02; d.m.position.y = y; d.hit.position.y = y + .15; } akte_sperre();
});
MOD_SAVE.push(['akte', () => 1, () => akte_sperre()]);
for (let n = 1; n <= 6; n++) KAP_BEGIN[n].push(() => akte_sperre());
window.__akte = { S: AKTE_S, lesen: n => akte_lesen(n), liste: AKTE }; // Testzugriff
